import {
  date,
  datetime,
  decimal,
  int,
  mysqlTable,
  text,
  varchar
} from 'drizzle-orm/mysql-core';

export const tbArea = mysqlTable('tb_area', {
  codigoAre: varchar('codigo_are', { length: 3 }).notNull().primaryKey(),
  descripcionAre: varchar('descripcion_are', { length: 40 }),
  codigoMod: varchar('codigo_mod', { length: 2 }),
  codigoCos: varchar('codigo_cos', { length: 14 }),
  incePro: varchar('ince_pro', { length: 1 }),
  codigoAnt: varchar('codigo_ant', { length: 3 }),
  noTransporte: varchar('no_transporte', { length: 1 }),
  fechaMod: datetime('fecha_mod'),
  costura: varchar('costura', { length: 1 }),
  produ: varchar('produ', { length: 1 }),
  estado: varchar('estado', { length: 1 }),
  depto: varchar('depto', { length: 2 })
});

export const tbMaestroEmpleados = mysqlTable('tb_maestro_empleados', {
  codigoEmp: varchar('codigo_emp', { length: 6 }).notNull().primaryKey(),
  cedulaId: varchar('cedula_id', { length: 16 }).notNull(),
  fEmision: date('f_emision'),
  fVencimie: date('f_vencimie'),
  nombre1: varchar('nombre1', { length: 20 }),
  nombre2: varchar('nombre2', { length: 20 }),
  apellido1: varchar('apellido1', { length: 20 }),
  apellido2: varchar('apellido2', { length: 20 }),
  nombreCompleto: varchar('nombre_completo', { length: 150 }),
  codigoSex: varchar('codigo_sex', { length: 1 }),
  codigoEc: varchar('codigo_ec', { length: 2 }),
  telefono: varchar('telefono', { length: 8 }),
  movil: varchar('movil', { length: 8 }),
  fechaNaci: date('fecha_naci'),
  inss: varchar('inss', { length: 15 }),
  codigoPai: varchar('codigo_pai', { length: 3 }),
  pais: varchar('pais', { length: 20 }),
  codigoDep: varchar('codigo_dep', { length: 3 }),
  departamento: varchar('departamento', { length: 20 }),
  codigoMun: varchar('codigo_mun', { length: 3 }),
  municipio: varchar('municipio', { length: 20 }),
  direccion: text('direccion'),
  mNombre1: varchar('m_nombre1', { length: 20 }),
  mNombre2: varchar('m_nombre2', { length: 20 }),
  mApellido1: varchar('m_apellido1', { length: 20 }),
  mApellido2: varchar('m_apellido2', { length: 20 }),
  mCedula: varchar('m_cedula', { length: 16 }),
  pNombre1: varchar('p_nombre1', { length: 20 }),
  pNombre2: varchar('p_nombre2', { length: 20 }),
  pApellido1: varchar('p_apellido1', { length: 20 }),
  pApellido2: varchar('p_apellido2', { length: 20 }),
  pCedula: varchar('p_cedula', { length: 16 }),
  cNombre1: varchar('c_nombre1', { length: 20 }),
  cNombre2: varchar('c_nombre2', { length: 20 }),
  cApellido1: varchar('c_apellido1', { length: 20 }),
  cApellido2: varchar('c_apellido2', { length: 20 }),
  cCedula: varchar('c_cedula', { length: 16 }),
  codigoEsmi: varchar('codigo_esmi', { length: 3 }),
  codigoMod: varchar('codigo_mod', { length: 2 }),
  codigoAre: varchar('codigo_are', { length: 3 }),
  codigoEst: varchar('codigo_est', { length: 2 }),
  codigoCar: varchar('codigo_car', { length: 4 }),
  reingreso: varchar('reingreso', { length: 1 }),
  codigoAnterior: varchar('codigo_anterior', { length: 6 }),
  bajaContratacion: varchar('baja_contratacion', { length: 1 }),
  fechaIngreso: date('fecha_ingreso'),
  fechaEgreso: date('fecha_egreso'),
  codigoMot: varchar('codigo_mot', { length: 2 }),
  codigoCau: varchar('codigo_cau', { length: 2 }),
  salarioBase: decimal('salario_base', { precision: 10, scale: 2 }),
  salarioViatico: decimal('salario_viatico', { precision: 10, scale: 2 }),
  salarioGeneral: decimal('salario_general', { precision: 10, scale: 2 }),
  observacion: text('observacion'),
  codigoPag: varchar('codigo_pag', { length: 2 }),
  noCuenta: varchar('no_cuenta', { length: 14 }),
  codigoCc: varchar('codigo_cc', { length: 10 }),
  codigoDep2: varchar('codigo_dep2', { length: 3 }),
  departamento2: varchar('departamento2', { length: 20 }),
  codigoMun2: varchar('codigo_mun2', { length: 3 }),
  municipio2: varchar('municipio2', { length: 20 }),
  codigoVac: varchar('codigo_vac', { length: 2 }),
  vacuna1: varchar('vacuna1', { length: 1 }),
  fechav1: date('fechav1'),
  vacuna2: varchar('vacuna2', { length: 1 }),
  fechav2: date('fechav2'),
  vacuna3: varchar('vacuna3', { length: 1 }),
  fechav3: date('fechav3'),
  vacuna4: varchar('vacuna4', { length: 1 }),
  fechav4: date('fechav4'),
  nombreVacuna: varchar('nombre_vacuna', { length: 20 }),
  huella: int('huella', {}),
  celularEstado: varchar('celular_estado', { length: 1 }),
  busEstado: varchar('bus_estado', { length: 1 })
});
